-- =============================================================================
-- V5 - Carga de países (ISO 3166-1 alpha-2), nome em português do Brasil e DDI.
-- Gerado por script (Intl.DisplayNames pt-BR do Node + tabela de DDI), ordenado
-- pelo nome. DDI compartilhado (ex: +1 para EUA/Canadá/Caribe) é esperado: o
-- país é identificado pelo CODE, o DDI é só o prefixo discado.
-- =============================================================================
INSERT INTO country (code, name, dial_code) VALUES
    ('AF', 'Afeganistão', '+93'),
    ('ZA', 'África do Sul', '+27'),
    ('AL', 'Albânia', '+355'),
    ('DE', 'Alemanha', '+49'),
    ('AD', 'Andorra', '+376'),
    ('AO', 'Angola', '+244'),
    ('AI', 'Anguila', '+1'),
    ('AQ', 'Antártida', '+672'),
    ('AG', 'Antígua e Barbuda', '+1'),
    ('SA', 'Arábia Saudita', '+966'),
    ('DZ', 'Argélia', '+213'),
    ('AR', 'Argentina', '+54'),
    ('AM', 'Armênia', '+374'),
    ('AW', 'Aruba', '+297'),
    ('AU', 'Austrália', '+61'),
    ('AT', 'Áustria', '+43'),
    ('AZ', 'Azerbaijão', '+994'),
    ('BS', 'Bahamas', '+1'),
    ('BD', 'Bangladesh', '+880'),
    ('BB', 'Barbados', '+1'),
    ('BH', 'Barein', '+973'),
    ('BE', 'Bélgica', '+32'),
    ('BZ', 'Belize', '+501'),
    ('BJ', 'Benin', '+229'),
    ('BM', 'Bermudas', '+1'),
    ('BY', 'Bielorrússia', '+375'),
    ('BO', 'Bolívia', '+591'),
    ('BA', 'Bósnia e Herzegovina', '+387'),
    ('BW', 'Botsuana', '+267'),
    ('BR', 'Brasil', '+55'),
    ('BN', 'Brunei', '+673'),
    ('BG', 'Bulgária', '+359'),
    ('BF', 'Burquina Faso', '+226'),
    ('BI', 'Burundi', '+257'),
    ('BT', 'Butão', '+975'),
    ('CV', 'Cabo Verde', '+238'),
    ('CM', 'Camarões', '+237'),
    ('KH', 'Camboja', '+855'),
    ('CA', 'Canadá', '+1'),
    ('QA', 'Catar', '+974'),
    ('KZ', 'Cazaquistão', '+7'),
    ('TD', 'Chade', '+235'),
    ('CL', 'Chile', '+56'),
    ('CN', 'China', '+86'),
    ('CY', 'Chipre', '+357'),
    ('VA', 'Cidade do Vaticano', '+39'),
    ('CO', 'Colômbia', '+57'),
    ('KM', 'Comores', '+269'),
    ('CD', 'Congo - Kinshasa', '+243'),
    ('KP', 'Coreia do Norte', '+850'),
    ('KR', 'Coreia do Sul', '+82'),
    ('CI', 'Costa do Marfim', '+225'),
    ('CR', 'Costa Rica', '+506'),
    ('HR', 'Croácia', '+385'),
    ('CU', 'Cuba', '+53'),
    ('CW', 'Curaçao', '+599'),
    ('DK', 'Dinamarca', '+45'),
    ('DJ', 'Djibuti', '+253'),
    ('DM', 'Dominica', '+1'),
    ('EG', 'Egito', '+20'),
    ('SV', 'El Salvador', '+503'),
    ('AE', 'Emirados Árabes Unidos', '+971'),
    ('EC', 'Equador', '+593'),
    ('ER', 'Eritreia', '+291'),
    ('SK', 'Eslováquia', '+421'),
    ('SI', 'Eslovênia', '+386'),
    ('ES', 'Espanha', '+34'),
    ('SZ', 'Essuatíni', '+268'),
    ('US', 'Estados Unidos', '+1'),
    ('EE', 'Estônia', '+372'),
    ('ET', 'Etiópia', '+251'),
    ('FJ', 'Fiji', '+679'),
    ('PH', 'Filipinas', '+63'),
    ('FI', 'Finlândia', '+358'),
    ('FR', 'França', '+33'),
    ('GA', 'Gabão', '+241'),
    ('GM', 'Gâmbia', '+220'),
    ('GH', 'Gana', '+233'),
    ('GE', 'Geórgia', '+995'),
    ('GI', 'Gibraltar', '+350'),
    ('GD', 'Granada', '+1'),
    ('GR', 'Grécia', '+30'),
    ('GL', 'Groenlândia', '+299'),
    ('GP', 'Guadalupe', '+590'),
    ('GU', 'Guam', '+1'),
    ('GT', 'Guatemala', '+502'),
    ('GG', 'Guernsey', '+44'),
    ('GY', 'Guiana', '+592'),
    ('GF', 'Guiana Francesa', '+594'),
    ('GN', 'Guiné', '+224'),
    ('GQ', 'Guiné Equatorial', '+240'),
    ('GW', 'Guiné-Bissau', '+245'),
    ('HT', 'Haiti', '+509'),
    ('HN', 'Honduras', '+504'),
    ('HK', 'Hong Kong, RAE da China', '+852'),
    ('HU', 'Hungria', '+36'),
    ('YE', 'Iêmen', '+967'),
    ('BV', 'Ilha Bouvet', '+47'),
    ('CX', 'Ilha Christmas', '+61'),
    ('IM', 'Ilha de Man', '+44'),
    ('NF', 'Ilha Norfolk', '+672'),
    ('AX', 'Ilhas Aland', '+358'),
    ('KY', 'Ilhas Cayman', '+1'),
    ('CC', 'Ilhas Cocos (Keeling)', '+61'),
    ('CK', 'Ilhas Cook', '+682'),
    ('FO', 'Ilhas Faroé', '+298'),
    ('GS', 'Ilhas Geórgia do Sul e Sandwich do Sul', '+500'),
    ('HM', 'Ilhas Heard e McDonald', '+672'),
    ('FK', 'Ilhas Malvinas', '+500'),
    ('MP', 'Ilhas Marianas do Norte', '+1'),
    ('MH', 'Ilhas Marshall', '+692'),
    ('UM', 'Ilhas Menores Distantes dos EUA', '+1'),
    ('PN', 'Ilhas Pitcairn', '+64'),
    ('SB', 'Ilhas Salomão', '+677'),
    ('TC', 'Ilhas Turcas e Caicos', '+1'),
    ('VI', 'Ilhas Virgens Americanas', '+1'),
    ('VG', 'Ilhas Virgens Britânicas', '+1'),
    ('IN', 'Índia', '+91'),
    ('ID', 'Indonésia', '+62'),
    ('IR', 'Irã', '+98'),
    ('IQ', 'Iraque', '+964'),
    ('IE', 'Irlanda', '+353'),
    ('IS', 'Islândia', '+354'),
    ('IL', 'Israel', '+972'),
    ('IT', 'Itália', '+39'),
    ('JM', 'Jamaica', '+1'),
    ('JP', 'Japão', '+81'),
    ('JE', 'Jersey', '+44'),
    ('JO', 'Jordânia', '+962'),
    ('KW', 'Kuwait', '+965'),
    ('LA', 'Laos', '+856'),
    ('LS', 'Lesoto', '+266'),
    ('LV', 'Letônia', '+371'),
    ('LB', 'Líbano', '+961'),
    ('LR', 'Libéria', '+231'),
    ('LY', 'Líbia', '+218'),
    ('LI', 'Liechtenstein', '+423'),
    ('LT', 'Lituânia', '+370'),
    ('LU', 'Luxemburgo', '+352'),
    ('MO', 'Macau, RAE da China', '+853'),
    ('MK', 'Macedônia do Norte', '+389'),
    ('MG', 'Madagascar', '+261'),
    ('MY', 'Malásia', '+60'),
    ('MW', 'Malaui', '+265'),
    ('MV', 'Maldivas', '+960'),
    ('ML', 'Mali', '+223'),
    ('MT', 'Malta', '+356'),
    ('MA', 'Marrocos', '+212'),
    ('MQ', 'Martinica', '+596'),
    ('MU', 'Maurício', '+230'),
    ('MR', 'Mauritânia', '+222'),
    ('YT', 'Mayotte', '+262'),
    ('MX', 'México', '+52'),
    ('MM', 'Mianmar (Birmânia)', '+95'),
    ('FM', 'Micronésia', '+691'),
    ('MZ', 'Moçambique', '+258'),
    ('MD', 'Moldávia', '+373'),
    ('MC', 'Mônaco', '+377'),
    ('MN', 'Mongólia', '+976'),
    ('ME', 'Montenegro', '+382'),
    ('MS', 'Montserrat', '+1'),
    ('NA', 'Namíbia', '+264'),
    ('NR', 'Nauru', '+674'),
    ('NP', 'Nepal', '+977'),
    ('NI', 'Nicarágua', '+505'),
    ('NE', 'Níger', '+227'),
    ('NG', 'Nigéria', '+234'),
    ('NU', 'Niue', '+683'),
    ('NO', 'Noruega', '+47'),
    ('NC', 'Nova Caledônia', '+687'),
    ('NZ', 'Nova Zelândia', '+64'),
    ('OM', 'Omã', '+968'),
    ('NL', 'Países Baixos', '+31'),
    ('BQ', 'Países Baixos Caribenhos', '+599'),
    ('PW', 'Palau', '+680'),
    ('PA', 'Panamá', '+507'),
    ('PG', 'Papua-Nova Guiné', '+675'),
    ('PK', 'Paquistão', '+92'),
    ('PY', 'Paraguai', '+595'),
    ('PE', 'Peru', '+51'),
    ('PF', 'Polinésia Francesa', '+689'),
    ('PL', 'Polônia', '+48'),
    ('PR', 'Porto Rico', '+1'),
    ('PT', 'Portugal', '+351'),
    ('KE', 'Quênia', '+254'),
    ('KG', 'Quirguistão', '+996'),
    ('KI', 'Quiribati', '+686'),
    ('GB', 'Reino Unido', '+44'),
    ('CF', 'República Centro-Africana', '+236'),
    ('CG', 'República do Congo', '+242'),
    ('DO', 'República Dominicana', '+1'),
    ('RE', 'Reunião', '+262'),
    ('RO', 'Romênia', '+40'),
    ('RW', 'Ruanda', '+250'),
    ('RU', 'Rússia', '+7'),
    ('EH', 'Saara Ocidental', '+212'),
    ('WS', 'Samoa', '+685'),
    ('AS', 'Samoa Americana', '+1'),
    ('SM', 'San Marino', '+378'),
    ('SH', 'Santa Helena', '+290'),
    ('LC', 'Santa Lúcia', '+1'),
    ('BL', 'São Bartolomeu', '+590'),
    ('KN', 'São Cristóvão e Névis', '+1'),
    ('MF', 'São Martinho', '+590'),
    ('PM', 'São Pedro e Miquelão', '+508'),
    ('ST', 'São Tomé e Príncipe', '+239'),
    ('VC', 'São Vicente e Granadinas', '+1'),
    ('SC', 'Seicheles', '+248'),
    ('SN', 'Senegal', '+221'),
    ('SL', 'Serra Leoa', '+232'),
    ('RS', 'Sérvia', '+381'),
    ('SG', 'Singapura', '+65'),
    ('SX', 'Sint Maarten', '+1'),
    ('SY', 'Síria', '+963'),
    ('SO', 'Somália', '+252'),
    ('LK', 'Sri Lanka', '+94'),
    ('SD', 'Sudão', '+249'),
    ('SS', 'Sudão do Sul', '+211'),
    ('SE', 'Suécia', '+46'),
    ('CH', 'Suíça', '+41'),
    ('SR', 'Suriname', '+597'),
    ('SJ', 'Svalbard e Jan Mayen', '+47'),
    ('TJ', 'Tadjiquistão', '+992'),
    ('TH', 'Tailândia', '+66'),
    ('TW', 'Taiwan', '+886'),
    ('TZ', 'Tanzânia', '+255'),
    ('CZ', 'Tchéquia', '+420'),
    ('IO', 'Território Britânico do Oceano Índico', '+246'),
    ('TF', 'Territórios Franceses do Sul', '+262'),
    ('PS', 'Territórios palestinos', '+970'),
    ('TL', 'Timor-Leste', '+670'),
    ('TG', 'Togo', '+228'),
    ('TK', 'Tokelau', '+690'),
    ('TO', 'Tonga', '+676'),
    ('TT', 'Trinidad e Tobago', '+1'),
    ('TN', 'Tunísia', '+216'),
    ('TM', 'Turcomenistão', '+993'),
    ('TR', 'Turquia', '+90'),
    ('TV', 'Tuvalu', '+688'),
    ('UA', 'Ucrânia', '+380'),
    ('UG', 'Uganda', '+256'),
    ('UY', 'Uruguai', '+598'),
    ('UZ', 'Uzbequistão', '+998'),
    ('VU', 'Vanuatu', '+678'),
    ('VE', 'Venezuela', '+58'),
    ('VN', 'Vietnã', '+84'),
    ('WF', 'Wallis e Futuna', '+681'),
    ('ZM', 'Zâmbia', '+260'),
    ('ZW', 'Zimbábue', '+263');
